// <auto-generated />
using System;
using CSharpAcademy.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpAcademy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330064238_ExpandirConteudoSeed")]
    partial class ExpandirConteudoSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalUsos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("ModuloId");

                    b.ToTable("AssistantFAQs");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estrelas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespostaAjudou")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespostaClara")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespostaCompleta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AssistantFeedbacks");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvaliacaoEstrelas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioFeedback")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdiomaUsado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelUsuarioNaMomentoPergunta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerguntaUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespostaAssistente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoRespostaMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsouFAQCache")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MediaAvaliacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMensagens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.CustomExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataCompletacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CustomExercises");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConquista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Conquistas");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpcoesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPRecompensa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.ToTable("Exercicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enunciado = "Qual palavra-chave permite que o compilador C# infira o tipo de uma variável automaticamente?",
                            Explicacao = "'var' é uma palavra-chave de inferência de tipo em tempo de compilação. O tipo é definido pelo compilador com base no valor atribuído.",
                            LicaoId = 1,
                            OpcoesJson = "[\"var\",\"dynamic\",\"object\",\"auto\"]",
                            Ordem = 1,
                            RespostaCorreta = "var",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 2,
                            Enunciado = "Em C#, 'string' e 'String' representam o mesmo tipo.",
                            Explicacao = "'string' é um alias da linguagem para 'System.String'. Ambos são idênticos e intercambiáveis.",
                            LicaoId = 1,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 3,
                            Enunciado = "Para declarar um valor que não pode ser alterado em C#, usa-se a palavra-chave: ____",
                            Explicacao = "'const' declara uma constante em tempo de compilação. Diferente de 'readonly', que é resolvida em tempo de execução.",
                            LicaoId = 1,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "const",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 4,
                            Enunciado = "Qual estrutura é mais adequada em C# para comparar uma variável contra múltiplos valores constantes?",
                            Explicacao = "'switch' é otimizado para comparação de um valor contra constantes. A switch expression do C# 8+ torna ainda mais conciso.",
                            LicaoId = 2,
                            OpcoesJson = "[\"switch\",\"if/else\",\"while\",\"do/while\"]",
                            Ordem = 1,
                            RespostaCorreta = "switch",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 5,
                            Enunciado = "É possível modificar os elementos de uma coleção durante uma iteração com foreach.",
                            Explicacao = "foreach não permite modificar a coleção durante a iteração. Para isso, use um loop for convencional ou crie uma nova lista.",
                            LicaoId = 2,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 6,
                            Enunciado = "O operador ternário em C# segue a sintaxe: condição ____ valorTrue : valorFalse",
                            Explicacao = "O operador ternário usa '?' para separar a condição do valor verdadeiro, e ':' para separar os dois valores.",
                            LicaoId = 2,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "?",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 7,
                            Enunciado = "Qual modificador de acesso restringe um método ao escopo da própria classe?",
                            Explicacao = "'private' limita o acesso ao membro apenas dentro da classe que o declara. É o modificador mais restritivo.",
                            LicaoId = 3,
                            OpcoesJson = "[\"private\",\"public\",\"protected\",\"internal\"]",
                            Ordem = 1,
                            RespostaCorreta = "private",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 8,
                            Enunciado = "Em C# é possível ter dois métodos com o mesmo nome desde que tenham assinaturas diferentes (sobrecarga).",
                            Explicacao = "Sobrecarga (overloading) permite múltiplos métodos com o mesmo nome, diferenciados pelo número ou tipo de parâmetros.",
                            LicaoId = 3,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 9,
                            Enunciado = "Um método que não retorna nenhum valor usa o tipo de retorno: ____",
                            Explicacao = "'void' indica ausência de retorno. Para métodos assíncronos sem retorno, usa-se 'Task' no lugar de 'async void'.",
                            LicaoId = 3,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "void",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 10,
                            Enunciado = "O que é um construtor em C#?",
                            Explicacao = "O construtor tem o mesmo nome da classe, não tem tipo de retorno e é chamado automaticamente ao instanciar o objeto com 'new'.",
                            LicaoId = 4,
                            OpcoesJson = "[\"Método especial que inicializa uma instância da classe\",\"Uma propriedade obrigatória\",\"Um tipo de herança\",\"Uma interface implícita\"]",
                            Ordem = 1,
                            RespostaCorreta = "Método especial que inicializa uma instância da classe",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 11,
                            Enunciado = "Uma classe pode ter múltiplos construtores com parâmetros diferentes.",
                            Explicacao = "Isso é sobrecarga de construtor. É comum ter um construtor padrão (sem parâmetros) e outros construtores com parâmetros.",
                            LicaoId = 4,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 12,
                            Enunciado = "Para criar uma nova instância de uma classe chamada Carro, usamos: var carro = ____ Carro();",
                            Explicacao = "'new' aloca memória e chama o construtor da classe para inicializar o objeto.",
                            LicaoId = 4,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "new",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 13,
                            Enunciado = "Qual símbolo é usado em C# para indicar que uma classe herda de outra?",
                            Explicacao = "Em C# usamos ':' para herança (e também para implementar interfaces). Ex: 'public class Cachorro : Animal'.",
                            LicaoId = 5,
                            OpcoesJson = "[\":\",\"extends\",\"inherits\",\"->\"]",
                            Ordem = 1,
                            RespostaCorreta = ":",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 14,
                            Enunciado = "Em C#, uma classe pode herdar de múltiplas classes ao mesmo tempo.",
                            Explicacao = "C# não suporta herança múltipla de classes. Para comportamento múltiplo, usa-se interfaces, que podem ser implementadas em quantidade ilimitada.",
                            LicaoId = 5,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 15,
                            Enunciado = "Para sobrescrever um método virtual na subclasse, usa-se a palavra-chave: ____",
                            Explicacao = "'override' indica que o método substitui a implementação da classe base marcada com 'virtual' ou 'abstract'.",
                            LicaoId = 5,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "override",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 16,
                            Enunciado = "Qual é a principal diferença entre Array e List<T> em C#?",
                            Explicacao = "Arrays têm tamanho definido na criação. List<T> cresce dinamicamente com Add() e encolhe com Remove().",
                            LicaoId = 6,
                            OpcoesJson = "[\"List<T> tem tamanho dinâmico, Array tem tamanho fixo\",\"Array é mais seguro que List<T>\",\"List<T> não aceita tipos genéricos\",\"São equivalentes em todos os aspectos\"]",
                            Ordem = 1,
                            RespostaCorreta = "List<T> tem tamanho dinâmico, Array tem tamanho fixo",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 17,
                            Enunciado = "O método List<T>.Add() adiciona elementos ao início da lista.",
                            Explicacao = "Add() adiciona ao FINAL da lista. Para adicionar no início ou em posição específica, use Insert(index, item).",
                            LicaoId = 6,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 18,
                            Enunciado = "Para obter a quantidade de elementos em uma List<T>, usa-se a propriedade: ____",
                            Explicacao = "List<T>.Count retorna o número de elementos. Arrays usam .Length. LINQ usa .Count() (método de extensão).",
                            LicaoId = 6,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "Count",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 19,
                            Enunciado = "Qual método LINQ retorna o primeiro elemento que satisfaz uma condição e lança exceção se não encontrar?",
                            Explicacao = "First() lança InvalidOperationException se não houver elemento. Use FirstOrDefault() para retornar null/default quando não encontrar.",
                            LicaoId = 7,
                            OpcoesJson = "[\"First()\",\"Select()\",\"Where()\",\"Take()\"]",
                            Ordem = 1,
                            RespostaCorreta = "First()",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 20,
                            Enunciado = "LINQ só funciona com coleções em memória (LINQ to Objects).",
                            Explicacao = "LINQ funciona com qualquer IQueryable<T> ou IEnumerable<T>: banco de dados via EF Core (LINQ to SQL), XML, arquivos, etc.",
                            LicaoId = 7,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 21,
                            Enunciado = "Para filtrar elementos em LINQ com uma condição, usa-se o método: ____",
                            Explicacao = "Where() filtra elementos que satisfazem um predicado. Retorna IEnumerable<T> com os elementos que passaram no filtro.",
                            LicaoId = 7,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "Where",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 22,
                            Enunciado = "O que acontece quando a runtime encontra um 'await' em um método assíncrono?",
                            Explicacao = "await suspende o método atual sem bloquear a thread. A thread retorna ao pool e pode processar outras requisições, melhorando a escalabilidade.",
                            LicaoId = 8,
                            OpcoesJson = "[\"A thread é liberada para outras tarefas enquanto aguarda\",\"O programa é pausado completamente\",\"Uma nova thread é criada automaticamente\",\"O método é cancelado\"]",
                            Ordem = 1,
                            RespostaCorreta = "A thread é liberada para outras tarefas enquanto aguarda",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 23,
                            Enunciado = "Todo método que usa 'await' deve ter 'async' em sua declaração.",
                            Explicacao = "'async' e 'await' são inseparáveis. 'async' marca o método como assíncrono e habilita o uso de 'await' dentro dele.",
                            LicaoId = 8,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 24,
                            Enunciado = "Um método assíncrono que não retorna valor deve ter tipo de retorno: ____",
                            Explicacao = "Use 'Task' (não 'async void') para métodos assíncronos sem retorno. 'async void' não pode ser aguardado e dificulta o tratamento de exceções.",
                            LicaoId = 8,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "Task",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 25,
                            Enunciado = "Qual é o principal benefício do Repository Pattern?",
                            Explicacao = "O Repository isola 'como' os dados são obtidos (SQL, EF, API externa) da lógica que decide 'o que' fazer com eles. Facilita testes e troca de infraestrutura.",
                            LicaoId = 9,
                            OpcoesJson = "[\"Desacoplar a lógica de negócio do acesso a dados\",\"Aumentar a velocidade das queries\",\"Reduzir a quantidade de código\",\"Substituir completamente o ORM\"]",
                            Ordem = 1,
                            RespostaCorreta = "Desacoplar a lógica de negócio do acesso a dados",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 26,
                            Enunciado = "No Repository Pattern, um Controller pode acessar o DbContext diretamente quando precisar de performance.",
                            Explicacao = "Controllers NUNCA devem acessar infraestrutura diretamente. Se precisar de performance, otimize o Repository (projeções, AsNoTracking, paginação).",
                            LicaoId = 9,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 27,
                            Enunciado = "Em Clean Architecture, o Controller deve depender da ____ do Repository, não da implementação concreta.",
                            Explicacao = "Dependência de abstrações (interfaces) é o Dependency Inversion Principle (D do SOLID). Permite trocar SQLite por SQL Server sem alterar o Controller.",
                            LicaoId = 9,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "interface",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 28,
                            Enunciado = "Qual modificador de acesso permite que membros sejam acessados apenas pela classe e suas subclasses?",
                            Explicacao = "'protected' é visível dentro da classe e em qualquer classe que herde dela. Ideal para membros que fazem parte do contrato de herança.",
                            LicaoId = 10,
                            OpcoesJson = "[\"protected\",\"private\",\"internal\",\"public\"]",
                            Ordem = 1,
                            RespostaCorreta = "protected",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 29,
                            Enunciado = "Uma propriedade com 'get' público e 'set' privado pode ser alterada de fora da classe.",
                            Explicacao = "Com 'private set', apenas a própria classe pode modificar o valor. Isso é encapsulamento: expõe leitura mas protege escrita.",
                            LicaoId = 10,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 30,
                            Enunciado = "Para criar uma propriedade que só pode ser definida durante a inicialização do objeto, usa-se o acessor: ____",
                            Explicacao = "'init' (C# 9+) permite definir o valor apenas no inicializador de objeto '{ }'. Depois disso, a propriedade torna-se somente leitura.",
                            LicaoId = 10,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "init",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 31,
                            Enunciado = "Qual método LINQ agrupa elementos por uma chave?",
                            Explicacao = "GroupBy agrupa elementos em subconjuntos por uma chave. Retorna IEnumerable<IGrouping<TKey, TElement>>.",
                            LicaoId = 11,
                            OpcoesJson = "[\"GroupBy\",\"Join\",\"Aggregate\",\"Partition\"]",
                            Ordem = 1,
                            RespostaCorreta = "GroupBy",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 32,
                            Enunciado = "O método Aggregate pode ser usado para concatenar strings de uma lista.",
                            Explicacao = "Aggregate é uma redução genérica. Pode somar, multiplicar, concatenar ou qualquer operação que combine dois elementos em um.",
                            LicaoId = 11,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 33,
                            Enunciado = "Para pegar apenas os primeiros N elementos de uma coleção em LINQ, usa-se o método: ____",
                            Explicacao = "Take(n) retorna os primeiros n elementos. Combinado com Skip, implementa paginação: Skip((page-1)*size).Take(size).",
                            LicaoId = 11,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "Take",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 34,
                            Enunciado = "Qual classe é usada para criar e controlar um CancellationToken?",
                            Explicacao = "CancellationTokenSource cria o token e expõe o método Cancel(). O token em si (CancellationToken) é passado para as operações que devem respeitar o cancelamento.",
                            LicaoId = 12,
                            OpcoesJson = "[\"CancellationTokenSource\",\"TaskCanceller\",\"CancellationController\",\"TokenFactory\"]",
                            Ordem = 1,
                            RespostaCorreta = "CancellationTokenSource",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 35,
                            Enunciado = "Quando um CancellationToken é cancelado, Task.Delay lança automaticamente uma OperationCanceledException.",
                            Explicacao = "A maioria dos métodos async do .NET aceita CancellationToken e lança OperationCanceledException quando cancelado. Isso inclui Task.Delay, HttpClient, EF Core, etc.",
                            LicaoId = 12,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 36,
                            Enunciado = "Para verificar manualmente se um token foi cancelado e lançar exceção, usa-se: ct.____IfCancellationRequested()",
                            Explicacao = "ThrowIfCancellationRequested() verifica ct.IsCancellationRequested e lança OperationCanceledException se verdadeiro. Use no início de loops ou operações longas.",
                            LicaoId = 12,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "Throw",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 37,
                            Enunciado = "Qual método aguarda a conclusão de TODAS as tasks de um array?",
                            Explicacao = "Task.WhenAll é assíncrono (retorna Task) e aguarda todas. Task.WaitAll bloqueia a thread atual — evite em código async.",
                            LicaoId = 13,
                            OpcoesJson = "[\"Task.WhenAll\",\"Task.WhenAny\",\"Task.WaitAll\",\"Task.RunAll\"]",
                            Ordem = 1,
                            RespostaCorreta = "Task.WhenAll",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 38,
                            Enunciado = "Task.WhenAny completa assim que QUALQUER uma das tasks terminar, mesmo que as outras ainda estejam rodando.",
                            Explicacao = "WhenAny retorna a primeira task que completar (com sucesso ou erro). As outras continuam executando em background.",
                            LicaoId = 13,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 39,
                            Enunciado = "Para executar múltiplas tasks em paralelo e aguardar todas, usamos: await Task.____( task1, task2 )",
                            Explicacao = "Task.WhenAll(task1, task2) inicia ambas simultaneamente e retorna quando as duas terminam. Muito mais eficiente que await task1; await task2 em sequência.",
                            LicaoId = 13,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "WhenAll",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 40,
                            Enunciado = "Qual é o principal objetivo do Factory Pattern?",
                            Explicacao = "Factory encapsula 'como' criar objetos. O cliente recebe um produto sem conhecer a classe concreta — depende apenas de uma abstração.",
                            LicaoId = 14,
                            OpcoesJson = "[\"Encapsular a criação de objetos\",\"Garantir uma única instância\",\"Separar interface de implementação\",\"Observar mudanças de estado\"]",
                            Ordem = 1,
                            RespostaCorreta = "Encapsular a criação de objetos",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 41,
                            Enunciado = "No Factory Pattern, o código cliente precisa conhecer todas as classes concretas que pode receber.",
                            Explicacao = "Esse é justamente o benefício: o cliente depende apenas da abstração (interface ou classe base). A factory decide qual concreto instanciar.",
                            LicaoId = 14,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Falso",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 42,
                            Enunciado = "Um método estático que cria e retorna instâncias de diferentes subclasses é chamado de ____ Factory.",
                            Explicacao = "Simple Factory é o padrão mais básico: um método (geralmente estático) que decide qual classe concreta instanciar com base em um parâmetro.",
                            LicaoId = 14,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "Simple",
                            Tipo = 3,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 43,
                            Enunciado = "Qual classe do .NET garante inicialização lazy e thread-safe de um Singleton?",
                            Explicacao = "Lazy<T> inicializa o valor apenas na primeira vez que .Value é acessado, de forma thread-safe. É a forma preferida de implementar Singleton em C#.",
                            LicaoId = 15,
                            OpcoesJson = "[\"Lazy<T>\",\"ThreadLocal<T>\",\"Concurrent<T>\",\"Once<T>\"]",
                            Ordem = 1,
                            RespostaCorreta = "Lazy<T>",
                            Tipo = 1,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 44,
                            Enunciado = "Em ASP.NET Core, AddSingleton registra uma instância que é criada uma única vez e reutilizada em toda a aplicação.",
                            Explicacao = "AddSingleton = uma instância por aplicação. AddScoped = uma por requisição HTTP. AddTransient = uma nova a cada injeção.",
                            LicaoId = 15,
                            OpcoesJson = "[\"Verdadeiro\",\"Falso\"]",
                            Ordem = 2,
                            RespostaCorreta = "Verdadeiro",
                            Tipo = 2,
                            XPRecompensa = 5
                        },
                        new
                        {
                            Id = 45,
                            Enunciado = "Para impedir que uma classe Singleton seja herdada, usa-se o modificador: ____",
                            Explicacao = "'sealed' impede herança. É recomendado em Singletons para garantir que ninguém possa criar subclasses que quebrem a unicidade da instância.",
                            LicaoId = 15,
                            OpcoesJson = "[]",
                            Ordem = 3,
                            RespostaCorreta = "sealed",
                            Tipo = 3,
                            XPRecompensa = 5
                        });
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Licao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConteudoTeoricoMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XPRecompensa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Licoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Variáveis em C#\n\nC# é uma linguagem fortemente tipada. Cada variável possui um tipo definido em tempo de compilação.\n\n### Tipos primitivos\n```csharp\nint idade = 25;\ndouble salario = 4500.50;\nbool ativo = true;\nstring nome = \"João\";\n```\n\n### Inferência de tipo com var\nA palavra-chave `var` permite que o compilador infira o tipo:\n```csharp\nvar cidade = \"São Paulo\"; // string\nvar populacao = 12_000_000; // int\n```\n\n### Constantes\n```csharp\nconst double PI = 3.14159;\n```",
                            Descricao = "int, string, bool, double e inferência de tipo",
                            ModuloId = 1,
                            Ordem = 1,
                            Titulo = "Variáveis e Tipos",
                            XPRecompensa = 10
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Controle de Fluxo\n\n### if/else\n```csharp\nif (nota >= 7)\n    Console.WriteLine(\"Aprovado\");\nelse\n    Console.WriteLine(\"Reprovado\");\n```\n\n### switch expression (C# moderno)\n```csharp\nvar resultado = nota switch\n{\n    >= 9 => \"A\",\n    >= 7 => \"B\",\n    >= 5 => \"C\",\n    _ => \"D\"\n};\n```\n\n### foreach\n```csharp\nvar nomes = new[] { \"Ana\", \"Bruno\", \"Carlos\" };\nforeach (var nome in nomes)\n    Console.WriteLine(nome);\n```",
                            Descricao = "if/else, switch, loops for e foreach",
                            ModuloId = 1,
                            Ordem = 2,
                            Titulo = "Controle de Fluxo",
                            XPRecompensa = 10
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Métodos em C#\n\n### Declaração básica\n```csharp\npublic int Somar(int a, int b) => a + b;\n```\n\n### Parâmetros opcionais\n```csharp\npublic string Saudar(string nome, string prefixo = \"Olá\")\n    => $\"{prefixo}, {nome}!\";\n```\n\n### Sobrecarga\nDois métodos com o mesmo nome mas parâmetros diferentes:\n```csharp\npublic double Calcular(double x) => x * x;\npublic double Calcular(double x, double y) => x * y;\n```",
                            Descricao = "Declaração, parâmetros, retorno e sobrecarga",
                            ModuloId = 1,
                            Ordem = 3,
                            Titulo = "Métodos e Funções",
                            XPRecompensa = 15
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Classes em C#\n\n```csharp\npublic class Produto\n{\n    public int Id { get; set; }\n    public string Nome { get; set; } = string.Empty;\n    public decimal Preco { get; set; }\n\n    public Produto(string nome, decimal preco)\n    {\n        Nome = nome;\n        Preco = preco;\n    }\n\n    public string Descricao() => $\"{Nome} - R$ {Preco:F2}\";\n}\n\n// Uso:\nvar produto = new Produto(\"Notebook\", 3500m);\nConsole.WriteLine(produto.Descricao());\n```",
                            Descricao = "Propriedades, construtores e instanciação",
                            ModuloId = 2,
                            Ordem = 1,
                            Titulo = "Classes e Objetos",
                            XPRecompensa = 15
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Herança\n\n```csharp\npublic class Animal\n{\n    public string Nome { get; set; } = string.Empty;\n    public virtual string EmitirSom() => \"...\";\n}\n\npublic class Cachorro : Animal\n{\n    public override string EmitirSom() => \"Au au!\";\n}\n```\n\n## Interfaces\n```csharp\npublic interface IVoador\n{\n    void Voar();\n}\n\npublic class Passaro : Animal, IVoador\n{\n    public override string EmitirSom() => \"Piu piu!\";\n    public void Voar() => Console.WriteLine(\"Voando...\");\n}\n```",
                            Descricao = "Herança, override e interfaces",
                            ModuloId = 2,
                            Ordem = 2,
                            Titulo = "Herança e Polimorfismo",
                            XPRecompensa = 20
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Coleções em C#\n\n### Array (tamanho fixo)\n```csharp\nint[] numeros = { 1, 2, 3, 4, 5 };\nConsole.WriteLine(numeros.Length); // 5\n```\n\n### List<T> (tamanho dinâmico)\n```csharp\nvar nomes = new List<string> { \"Ana\", \"Bruno\" };\nnomes.Add(\"Carlos\");\nnomes.Remove(\"Ana\");\nConsole.WriteLine(nomes.Count); // 2\n```\n\n### Dictionary<TKey, TValue>\n```csharp\nvar capitais = new Dictionary<string, string>\n{\n    [\"SP\"] = \"São Paulo\",\n    [\"RJ\"] = \"Rio de Janeiro\"\n};\n```",
                            Descricao = "List<T>, Array e operações comuns",
                            ModuloId = 3,
                            Ordem = 1,
                            Titulo = "Listas e Arrays",
                            XPRecompensa = 20
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## LINQ — Language Integrated Query\n\n```csharp\nvar numeros = new List<int> { 5, 3, 8, 1, 9, 2 };\n\n// Filtrar\nvar pares = numeros.Where(n => n % 2 == 0).ToList();\n\n// Transformar\nvar dobrados = numeros.Select(n => n * 2).ToList();\n\n// Ordenar\nvar ordenados = numeros.OrderBy(n => n).ToList();\n\n// Primeiro elemento\nvar maior = numeros.Max();\nvar primeiro = numeros.First(n => n > 5);\n\n// Encadeamento\nvar resultado = numeros\n    .Where(n => n > 3)\n    .OrderByDescending(n => n)\n    .Select(n => $\"Número: {n}\")\n    .ToList();\n```",
                            Descricao = "Where, Select, OrderBy e First",
                            ModuloId = 3,
                            Ordem = 2,
                            Titulo = "LINQ Básico",
                            XPRecompensa = 25
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Programação Assíncrona\n\nasync/await permite executar operações sem bloquear a thread principal.\n\n```csharp\npublic async Task<string> BuscarDadosAsync(int id)\n{\n    // Simula chamada a banco/API\n    await Task.Delay(100);\n    return $\"Dados do id {id}\";\n}\n\n// Chamando:\nvar dados = await BuscarDadosAsync(42);\n```\n\n### Múltiplas tasks em paralelo\n```csharp\nvar task1 = BuscarDadosAsync(1);\nvar task2 = BuscarDadosAsync(2);\n\nvar resultados = await Task.WhenAll(task1, task2);\n```\n\n### Método sem retorno\n```csharp\npublic async Task SalvarAsync(string dados)\n{\n    await File.WriteAllTextAsync(\"arquivo.txt\", dados);\n}\n```",
                            Descricao = "Tarefas assíncronas com Task e async/await",
                            ModuloId = 4,
                            Ordem = 1,
                            Titulo = "async/await",
                            XPRecompensa = 30
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Repository Pattern\n\nIsola a lógica de acesso a dados da lógica de negócio.\n\n```csharp\n// 1. Interface — define o contrato\npublic interface IProdutoRepository\n{\n    Task<Produto?> ObterPorIdAsync(int id);\n    Task<IEnumerable<Produto>> ObterTodosAsync();\n    Task AdicionarAsync(Produto produto);\n    Task<bool> SalvarAsync();\n}\n\n// 2. Implementação — detalhe de infraestrutura\npublic class ProdutoRepository(AppDbContext ctx) : IProdutoRepository\n{\n    public async Task<Produto?> ObterPorIdAsync(int id)\n        => await ctx.Produtos.FindAsync(id);\n\n    public async Task AdicionarAsync(Produto produto)\n        => await ctx.Produtos.AddAsync(produto);\n\n    public async Task<bool> SalvarAsync()\n        => await ctx.SaveChangesAsync() > 0;\n}\n\n// 3. Controller — depende da interface, nunca da implementação\npublic class ProdutoController(IProdutoRepository repo) : ControllerBase { }\n```",
                            Descricao = "Abstraindo o acesso a dados com Repository",
                            ModuloId = 5,
                            Ordem = 1,
                            Titulo = "Repository Pattern",
                            XPRecompensa = 35
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Encapsulamento\n\nEncapsulamento esconde os detalhes internos e expõe apenas o necessário.\n\n### Modificadores de acesso\n```csharp\npublic class ContaBancaria\n{\n    private decimal _saldo;           // só a classe acessa\n    protected string Titular { get; } // classe + herdeiras\n    internal int AgenciaId { get; }   // mesmo assembly\n    public decimal Saldo => _saldo;   // leitura pública, escrita privada\n\n    public void Depositar(decimal valor)\n    {\n        if (valor <= 0) throw new ArgumentException(\"Valor inválido\");\n        _saldo += valor;\n    }\n\n    public bool Sacar(decimal valor)\n    {\n        if (valor > _saldo) return false;\n        _saldo -= valor;\n        return true;\n    }\n}\n```\n\n### Propriedades com validação\n```csharp\npublic class Produto\n{\n    private decimal _preco;\n\n    public decimal Preco\n    {\n        get => _preco;\n        set\n        {\n            if (value < 0) throw new ArgumentException(\"Preço não pode ser negativo\");\n            _preco = value;\n        }\n    }\n}\n```\n\n### init — propriedade somente para construção\n```csharp\npublic class Pedido\n{\n    public int Id { get; init; }     // só pode ser definido no new {}\n    public DateTime Criado { get; } = DateTime.UtcNow;\n}\n\nvar pedido = new Pedido { Id = 42 }; // OK\n// pedido.Id = 1;                    // ERRO em tempo de compilação\n```",
                            Descricao = "Modificadores de acesso, propriedades e princípio do encapsulamento",
                            ModuloId = 2,
                            Ordem = 3,
                            Titulo = "Encapsulamento",
                            XPRecompensa = 20
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## LINQ Avançado\n\n### GroupBy — agrupa por chave\n```csharp\nvar pedidos = new List<Pedido> { ... };\n\nvar porCliente = pedidos\n    .GroupBy(p => p.ClienteId)\n    .Select(g => new {\n        ClienteId = g.Key,\n        Total = g.Sum(p => p.Valor),\n        Quantidade = g.Count()\n    });\n```\n\n### Join — combina duas coleções\n```csharp\nvar resultado = clientes.Join(\n    pedidos,\n    c => c.Id,\n    p => p.ClienteId,\n    (c, p) => new { c.Nome, p.Valor }\n);\n```\n\n### Aggregate — redução customizada\n```csharp\nvar numeros = new[] { 1, 2, 3, 4, 5 };\n\n// Equivalente a um fold/reduce\nvar produto = numeros.Aggregate(1, (acc, n) => acc * n); // 120\nvar frase = new[] { \"C#\", \"é\", \"incrível\" }\n    .Aggregate((a, b) => $\"{a} {b}\"); // \"C# é incrível\"\n```\n\n### Any, All, Contains\n```csharp\nvar tem18 = idades.Any(i => i >= 18);\nvar todosMaiores = idades.All(i => i >= 0);\nvar temDez = numeros.Contains(10);\n```\n\n### Paginação\n```csharp\nint pagina = 2, tamanho = 10;\nvar paginado = produtos\n    .OrderBy(p => p.Nome)\n    .Skip((pagina - 1) * tamanho)\n    .Take(tamanho)\n    .ToList();\n```",
                            Descricao = "GroupBy, Join, Aggregate e projeções complexas",
                            ModuloId = 3,
                            Ordem = 3,
                            Titulo = "LINQ Avançado",
                            XPRecompensa = 25
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## CancellationToken\n\nPermite cancelar operações assíncronas de forma cooperativa (sem matar threads à força).\n\n### Criando e passando o token\n```csharp\nusing var cts = new CancellationTokenSource();\ncts.CancelAfter(TimeSpan.FromSeconds(5)); // cancela após 5s\n\ntry\n{\n    var resultado = await BuscarDadosAsync(cts.Token);\n}\ncatch (OperationCanceledException)\n{\n    Console.WriteLine(\"Operação cancelada!\");\n}\n```\n\n### Recebendo e respeitando o token\n```csharp\npublic async Task<string> BuscarDadosAsync(CancellationToken ct = default)\n{\n    // Verifica antes de operações longas\n    ct.ThrowIfCancellationRequested();\n\n    await Task.Delay(2000, ct); // Task.Delay já respeita o token\n\n    return \"dados\";\n}\n```\n\n### Em ASP.NET Core\nOs controllers recebem o token automaticamente:\n```csharp\n[HttpGet]\npublic async Task<IActionResult> Get(CancellationToken ct)\n{\n    var dados = await _repo.ObterTodosAsync(ct);\n    return Ok(dados);\n}\n```\nSe o cliente desconectar, `ct` é cancelado automaticamente.",
                            Descricao = "Cancelamento cooperativo de operações assíncronas",
                            ModuloId = 4,
                            Ordem = 2,
                            Titulo = "CancellationToken",
                            XPRecompensa = 30
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Paralelismo com Tasks\n\n### Task.WhenAll — aguarda TODAS as tasks\n```csharp\n// Sem paralelismo (sequencial — lento)\nvar u1 = await BuscarUsuarioAsync(1); // espera\nvar u2 = await BuscarUsuarioAsync(2); // espera\n\n// Com paralelismo — muito mais rápido!\nvar task1 = BuscarUsuarioAsync(1);\nvar task2 = BuscarUsuarioAsync(2);\nvar (u1, u2) = await (task1, task2); // ambas simultâneas\n\n// Ou com array:\nvar ids = new[] { 1, 2, 3, 4 };\nvar usuarios = await Task.WhenAll(ids.Select(id => BuscarUsuarioAsync(id)));\n```\n\n### Task.WhenAny — aguarda a PRIMEIRA a completar\n```csharp\n// Cache race: quem responder primeiro vence\nvar taskBanco = BuscarNoBancoAsync(id);\nvar taskCache = BuscarNoCacheAsync(id);\n\nvar primeira = await Task.WhenAny(taskBanco, taskCache);\nvar resultado = await primeira; // garante exceções propagadas\n```\n\n### Cuidados\n```csharp\n// Task.WhenAll propaga TODAS as exceções\ntry\n{\n    await Task.WhenAll(task1, task2, task3);\n}\ncatch (Exception ex)\n{\n    // ex contém apenas a primeira — inspecione task1.Exception, etc.\n}\n```",
                            Descricao = "Execução paralela de múltiplas tasks assíncronas",
                            ModuloId = 4,
                            Ordem = 3,
                            Titulo = "Task.WhenAll e Task.WhenAny",
                            XPRecompensa = 30
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Factory Pattern\n\nEncapsula a criação de objetos, permitindo que o código cliente não conheça as classes concretas.\n\n### Simple Factory\n```csharp\npublic abstract class Notificacao\n{\n    public abstract void Enviar(string mensagem);\n}\n\npublic class NotificacaoEmail : Notificacao\n{\n    public override void Enviar(string msg) => Console.WriteLine($\"Email: {msg}\");\n}\n\npublic class NotificacaoSms : Notificacao\n{\n    public override void Enviar(string msg) => Console.WriteLine($\"SMS: {msg}\");\n}\n\npublic static class NotificacaoFactory\n{\n    public static Notificacao Criar(string tipo) => tipo switch\n    {\n        \"email\" => new NotificacaoEmail(),\n        \"sms\"   => new NotificacaoSms(),\n        _ => throw new ArgumentException($\"Tipo desconhecido: {tipo}\")\n    };\n}\n\n// Uso — o cliente não instancia diretamente\nvar notif = NotificacaoFactory.Criar(\"email\");\nnotif.Enviar(\"Pedido confirmado!\");\n```\n\n### Por que usar?\n- O tipo concreto pode mudar sem alterar o código cliente\n- Centraliza a lógica de criação (configurações, validações)\n- Facilita testes (pode injetar factory mockada)",
                            Descricao = "Criando objetos sem expor a lógica de construção",
                            ModuloId = 5,
                            Ordem = 2,
                            Titulo = "Factory Pattern",
                            XPRecompensa = 35
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Singleton Pattern\n\nGarante que uma classe tenha apenas uma instância durante toda a vida da aplicação.\n\n### Implementação thread-safe com Lazy<T>\n```csharp\npublic sealed class ConfiguracaoApp\n{\n    // Lazy<T> garante thread-safety e lazy initialization\n    private static readonly Lazy<ConfiguracaoApp> _instancia =\n        new(() => new ConfiguracaoApp());\n\n    public static ConfiguracaoApp Instancia => _instancia.Value;\n\n    public string Ambiente { get; private set; }\n    public string ConnectionString { get; private set; }\n\n    private ConfiguracaoApp()\n    {\n        Ambiente = Environment.GetEnvironmentVariable(\"ASPNETCORE_ENVIRONMENT\") ?? \"Development\";\n        ConnectionString = \"Data Source=app.db\";\n    }\n}\n\n// Uso\nvar config = ConfiguracaoApp.Instancia;\nConsole.WriteLine(config.Ambiente);\n```\n\n### Em ASP.NET Core — prefira o container de DI\n```csharp\n// Program.cs — AddSingleton registra uma única instância\nbuilder.Services.AddSingleton<ICacheService, MemoryCacheService>();\n\n// O container garante a unicidade e facilita os testes\n// (diferente do Singleton estático que dificulta mock)\n```\n\n### Quando usar?\n- Configurações globais, loggers, conexões com recursos únicos\n- **Evite** para estado mutável compartilhado — causa bugs em concorrência",
                            Descricao = "Garantindo uma única instância com thread safety",
                            ModuloId = 5,
                            Ordem = 3,
                            Titulo = "Singleton Pattern",
                            XPRecompensa = 35
                        });
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Variáveis, tipos, operadores e controle de fluxo",
                            NivelMinimo = 1,
                            Ordem = 1,
                            Titulo = "Fundamentos C#"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Classes, herança, polimorfismo e encapsulamento",
                            NivelMinimo = 1,
                            Ordem = 2,
                            Titulo = "Orientação a Objetos"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "List, Dictionary, Array e consultas LINQ",
                            NivelMinimo = 2,
                            Ordem = 3,
                            Titulo = "Coleções e LINQ"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Programação assíncrona, Tasks e threading",
                            NivelMinimo = 2,
                            Ordem = 4,
                            Titulo = "Async/Await e Concorrência"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Repository, Factory, Singleton e outros padrões",
                            NivelMinimo = 3,
                            Ordem = 5,
                            Titulo = "Design Patterns"
                        });
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Progresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPGanho")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("UsuarioId", "LicaoId")
                        .IsUnique();

                    b.ToTable("Progressos");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.RespostaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Correta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RespostasUsuarios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelAtual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreakAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreakMaximo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimoEstudo")
                        .HasColumnType("TEXT");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFAQ", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId");

                    b.HasOne("CSharpAcademy.API.Domain.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFeedback", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.AI.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatMessage", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.AI.ChatSession", "ChatSession")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChatSessionId");

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatSession", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.CustomExercise", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Conquista", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Exercicio", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany("Exercicios")
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Licao", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Modulo", "Modulo")
                        .WithMany("Licoes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Progresso", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany("Progressos")
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("Progressos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.RespostaUsuario", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Exercicio", "Exercicio")
                        .WithMany("RespostasUsuarios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatSession", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Exercicio", b =>
                {
                    b.Navigation("RespostasUsuarios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Licao", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Progressos");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Modulo", b =>
                {
                    b.Navigation("Licoes");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Usuario", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatSessions");

                    b.Navigation("Conquistas");

                    b.Navigation("Progressos");
                });
#pragma warning restore 612, 618
        }
    }
}
