// <auto-generated />
using System;
using CSharpAcademy.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpAcademy.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pergunta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalUsos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("ModuloId");

                    b.ToTable("AssistantFAQs");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estrelas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespostaAjudou")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespostaClara")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RespostaCompleta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatMessageId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AssistantFeedbacks");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AvaliacaoEstrelas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChatSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioFeedback")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IdiomaUsado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NivelUsuarioNaMomentoPergunta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerguntaUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RespostaAssistente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TempoRespostaMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsouFAQCache")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MediaAvaliacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalMensagens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.CustomExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataCompletacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CustomExercises");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpcoesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RespostaCorreta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPRecompensa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Licao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConteudoTeoricoMarkdown")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ModuloId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XPRecompensa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Licoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Variáveis em C#\n\nC# é uma linguagem fortemente tipada...",
                            Descricao = "int, string, bool, double e inferência de tipo",
                            ModuloId = 1,
                            Ordem = 1,
                            Titulo = "Variáveis e Tipos",
                            XPRecompensa = 10
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Controle de Fluxo\n\nDecisões e repetições em C#...",
                            Descricao = "if/else, switch, loops for e foreach",
                            ModuloId = 1,
                            Ordem = 2,
                            Titulo = "Controle de Fluxo",
                            XPRecompensa = 10
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Métodos\n\nMétodos encapsulam comportamento...",
                            Descricao = "Declaração, parâmetros, retorno e sobrecarga",
                            ModuloId = 1,
                            Ordem = 3,
                            Titulo = "Métodos e Funções",
                            XPRecompensa = 15
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Classes em C#\n\nClasses são moldes para objetos...",
                            Descricao = "Propriedades, construtores e instanciação",
                            ModuloId = 2,
                            Ordem = 1,
                            Titulo = "Classes e Objetos",
                            XPRecompensa = 15
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Herança\n\nReutilização de código através de herança...",
                            Descricao = "Herança, override e interfaces",
                            ModuloId = 2,
                            Ordem = 2,
                            Titulo = "Herança e Polimorfismo",
                            XPRecompensa = 20
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Coleções\n\nListas são coleções dinâmicas...",
                            Descricao = "List<T>, Array e operações comuns",
                            ModuloId = 3,
                            Ordem = 1,
                            Titulo = "Listas e Arrays",
                            XPRecompensa = 20
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## LINQ\n\nLanguage Integrated Query permite consultas...",
                            Descricao = "Where, Select, OrderBy e First",
                            ModuloId = 3,
                            Ordem = 2,
                            Titulo = "LINQ Básico",
                            XPRecompensa = 25
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Programação Assíncrona\n\nasync/await simplifica código assíncrono...",
                            Descricao = "Tarefas assíncronas com Task e async/await",
                            ModuloId = 4,
                            Ordem = 1,
                            Titulo = "async/await",
                            XPRecompensa = 30
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            ConteudoTeoricoMarkdown = "## Repository Pattern\n\nO padrão Repository isola a lógica de acesso a dados...",
                            Descricao = "Abstraindo o acesso a dados com Repository",
                            ModuloId = 5,
                            Ordem = 1,
                            Titulo = "Repository Pattern",
                            XPRecompensa = 35
                        });
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelMinimo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            Descricao = "Variáveis, tipos, operadores e controle de fluxo",
                            NivelMinimo = 1,
                            Ordem = 1,
                            Titulo = "Fundamentos C#"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            Descricao = "Classes, herança, polimorfismo e encapsulamento",
                            NivelMinimo = 1,
                            Ordem = 2,
                            Titulo = "Orientação a Objetos"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            Descricao = "List, Dictionary, Array e consultas LINQ",
                            NivelMinimo = 2,
                            Ordem = 3,
                            Titulo = "Coleções e LINQ"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            Descricao = "Programação assíncrona, Tasks e threading",
                            NivelMinimo = 2,
                            Ordem = 4,
                            Titulo = "Async/Await e Concorrência"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            Descricao = "Repository, Factory, Singleton e outros padrões",
                            NivelMinimo = 3,
                            Ordem = 5,
                            Titulo = "Design Patterns"
                        });
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Progresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("LicaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XPGanho")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LicaoId");

                    b.HasIndex("UsuarioId", "LicaoId")
                        .IsUnique();

                    b.ToTable("Progressos");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.RespostaUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Correta")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RespostasUsuarios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelAtual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFAQ", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId");

                    b.HasOne("CSharpAcademy.API.Domain.Modulo", "Modulo")
                        .WithMany()
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.AssistantFeedback", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.AI.ChatMessage", "ChatMessage")
                        .WithMany()
                        .HasForeignKey("ChatMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChatMessage");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatMessage", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.AI.ChatSession", "ChatSession")
                        .WithMany("Mensagens")
                        .HasForeignKey("ChatSessionId");

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatSession", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("ChatSessions")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.CustomExercise", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany()
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Exercicio", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany("Exercicios")
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Licao", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Modulo", "Modulo")
                        .WithMany("Licoes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Progresso", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Licao", "Licao")
                        .WithMany("Progressos")
                        .HasForeignKey("LicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany("Progressos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.RespostaUsuario", b =>
                {
                    b.HasOne("CSharpAcademy.API.Domain.Exercicio", "Exercicio")
                        .WithMany("RespostasUsuarios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpAcademy.API.Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.AI.ChatSession", b =>
                {
                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Exercicio", b =>
                {
                    b.Navigation("RespostasUsuarios");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Licao", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Progressos");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Modulo", b =>
                {
                    b.Navigation("Licoes");
                });

            modelBuilder.Entity("CSharpAcademy.API.Domain.Usuario", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatSessions");

                    b.Navigation("Progressos");
                });
#pragma warning restore 612, 618
        }
    }
}
